source "http://rubygems.org"

#source 'http://nexus-repo.cgmp-osa.com.br/repository/rubygems-registry/'

gem 'capybara', '~> 3.14.0'
gem 'childprocess', '~> 0.9.0'
gem 'cpf_faker'
gem 'cucumber', '~> 3.1.2'
gem 'pry'
gem 'rspec', '~> 3.8.0'
gem 'selenium-webdriver', '<= 3.141.0'
gem 'site_prism'